### ISSUE TITLE
Array parsing isn't working as expected

### ISSUE THREAD

**Issue by galindro** [mrbaseman/parse_yaml#1]
@mrbaseman 

I'm using exactly the same example showed in README.md for this test.

This is the file:

```yaml
---
global:
  input:
    - "main.c"
    - "main.h"
  flags: [ "-O3", "-fpic" ]
  sample_input:
    -  { property1: value1, property2: value2 }
    -  { property1: "value 3", property2: 'value 4' }
  licence: |
    this is published under
    open source license
    in the hope that it would 
    be useful
...
```

This is the result:

 ```bash
global__input__1="main.c"
global__input__2="main.h"
global__flags="1- "-O3"
global__flags="1- "-O3 1- "-fpic"
global__sample_input__1property1="value1" 
global__sample_input__1property2="value2"
global__sample_input__1property1="value 3"
global__sample_input__1property2="value 4"
global__licence="this is published under"
global__licence="this is published under open source license"
global__licence="this is published under open source license in the hope that it would"
global__licence="this is published under open source license in the hope that it would be useful"
__=" global"
global__=" global__input global__flags global__sample_input global__licence"
global__input__=" global__input__1 global__input__2"
global__sample_input__=" global__sample_input__1 global__sample_input__1property1 global__sample_input__1property2 global__sample_input__2"
```

These lines:

```bash
global__sample_input__1property1="value1" 
global__sample_input__1property2="value2"
global__sample_input__1property1="value 3"
global__sample_input__1property2="value 4"
```

Should be like bellow, not like above
```bash
global_sample_input_1_property1="value1"
global_sample_input_1_property2="value2"
global_sample_input_2_property1="value 3"
global_sample_input_2_property2="value 4"
```

**Comment by galindro** [comment]
Bash version:
```bash
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by mrbaseman** [comment]
@galindro: I have tried to reproduce this on my Ubuntu 16.04 LTS. I have installed the bash version that you have mentioned but still couldn't reproduce it. I doubt it's the bash version which is causing the trouble. I believe something in your environment or the character set is interfering with the parser script.
The separator should be a single underscore by default, but two underscores are used already on the first line of your output. The quotes for the flags are wrong, too.
To debug the problem, you can:
- double check the output of `env` and see if there are any of the variables used in the script ( `separator`, `prefix`, `s`, `w`, `fs`, and `i`)
- double check the input file with a hex editor, to see if there are any non-printable characters that shouldn't be there (I have noticed that `unix2dos` breaks the yaml file, but with a different result than what you have observed).
- `export fs=#` and remove the second, (lenghty) awk statement. Then, the output should look like below (It is a preprocessed representation of the input which can be seen as some kind of table with a '#' sign as column separator - by default a non-printable character` \034` is used, therefore the `export` to make them visible. The first column is the indentation with space characters as in the original file. The second column is the variable name of the entry, and the third one is the value. All yaml syntax has been parsed at that point, and the final `awk` statement, which you should remove for this test, collects the values and variable names and puts together the shell variables):
```
#global#
  #input#
    ##main.c
    ##main.h
  #flags#
    ##-O3
    ##-fpic
  #sample_input#
    ##
      #property1#value1
      #property2#value2
    ##
      #property1#value 3
      #property2#value 4
  #licence#this is published under\nopen source license\nin the hope that it would \nbe useful\n
```

**Comment by galindro** [comment]
Ok @mrbaseman . Let's close this issue for now.

**Comment by mrbaseman** [comment]
ok. But if you need any further assistance in debugging, please let me know. Also, when you have identified the root cause for this unexpected behavior, could you update the issue, please, so  that others who might observe something similar, can solve the problem more quickly.
I might also make the code more robust, but I would have to be able to reproduce it first.

**Comment by mrbaseman** [comment]
@galindro did you copy&paste the function into an interactive shell? I have noticed that there were some tab characters in use for indentation which have triggered tab expansion when pasting the function into a terminal. This has lead to strange results. I have usually sourced the script, so I didn't notice this effect before. It's fixed now by replacing all tabs by 8 spaces.

**Comment by galindro** [comment]
No. What I did was copy and paste into a file and sourced it from terminal
