### ISSUE TITLE
awk: cmd. line:37: Call to undefined function

### ISSUE THREAD

**Issue by duxbuse** [mrbaseman/parse_yaml#2]
When cloning this repo, and running
`source parse_yaml.sh`
then
`parse_yaml sample.yml`

I get `awk: cmd. line:37: Call to undefined function`

Still seem to get all the values printing out correctly, but also getting this error.

**Comment by mrbaseman** [comment]
line 37 of an awk command can only be in the last part where the output is produced and sorted (the first awk call has less than 37 lines).

Maybe your awk does not support asorti()? Or it throws a warning and falls back to asort()? 
I'm using Gnu awk on Ubuntu and I don't see the message. 

Do you also get the lists of items like `global_unordered_set_=" global_unordered_set_1 global_unordered_set_2 global_unordered_set_3"`?
If you don't need those, you probably can get rid of the message by removing the `END{ ... }` section of the last awk call, where presumably the error occurs.

Any feedback is appreciated to make the code more portable.

**Comment by duxbuse** [comment]
Ahh ok, yeah im on mac, ill play around with it and see.

**Comment by prologic** [comment]
I also get the same error:

```sh
# ./test.sh
awk: cmd. line:37: Call to undefined function
CLOUDINIT_chpasswd_expire='False'
CLOUDINIT_disable_root='False'
CLOUDINIT_hostname='ulinux-test'
CLOUDINIT_manage_etc_hosts='true'
CLOUDINIT_package_upgrade='true'
CLOUDINIT_password='/78'
CLOUDINIT_ssh_authorized_keys_1='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDo9UKNJ6X+LUxY9E2Ne3IxluaBTQWE0nCgyVfPHgSJhrI1HDiKcwc2S10kzMOnWco47sOb0Te4/tOHh+jlBbSTiW2CqQpIkZ8Bz4d1VXIPpUCUreP8gSuWxWNrdiU3TpfaeLSn0BkQhssvUhooAVPcRlgpmLETeGVlY1G2Qc1YcrQusz5E/5vLp4wkycZnGvHJ9+R5M2gn12Wnj+Fg8xMdqsvKmtBasPTX9YcJxVj/CBJZUB5impNg7ml9mESGDOpU11H9UWLUiDjIOmiDu3baNUiUmUnrUG44HBnstvbglEEOjsywML9xB81iZkA8RPluFpMU/+BWPI3nIKyRZn2p prologic@Jamess-MacBook.local'
CLOUDINIT_user='root'
EDITOR='vi'
HOME='/root'
HOSTNAME='ulinux'
IFS='
'
INPUTRC='/etc/inputrc'
LESS='-R'
LINENO=''
LOGNAME='root'
OPTIND='1'
PATH='/sbin:/usr/sbin:/bin:/usr/bin'
PPID='162'
PS1='\[\033[1m\]\$ \[\033[0m\]'
PS2='\[\033[1m\]> \[\033[0m\]'
PS4='+ '
PWD='/root'
SHELL='/bin/sh'
SHLVL='2'
SSH_AUTH_SOCK='/tmp/dropbear-b9f21937/auth-43cae10e-6'
SSH_CLIENT='10.0.0.109 49647 22'
SSH_CONNECTION='10.0.0.109 49647 10.0.0.137 22'
SSH_TTY='/dev/pts/0'
TERM='xterm-256color'
USER='root'
#
```

It still seems to work though :) So that's good.

I'm using this to parse cloudinit `user-data` config for [uLinux](https://github.com/prologic/ulinux) which has a busybox userland, so yeah `awk` is probably missing the `sort` command. Why sort anyway? It doesn't seem that important here?

**Comment by mrbaseman** [comment]
@prologic yes, cool.  Sorting the indices was just for better readability, but you are right, it does not add a real value. Could you test again with the current master, please?

**Comment by prologic** [comment]
I already have! it works very nicely. I plan to include it in an upcoming version/commit of [ulinux](https://github.com/prologic/uliniux) for full cloud-init support. Stay tuned :)
