### ISSUE TITLE
parse_yaml:87: bad math expression: operand expected at `\"''

### ISSUE THREAD

**Issue by notify-bibi** [mrbaseman/parse_yaml#27]
before:
![image](https://github.com/user-attachments/assets/99c9d404-c086-4217-aa87-ca47b2e1f87c)

fix:
![image](https://github.com/user-attachments/assets/97d099b7-54ed-4236-8a27-9cfcc989b061)

after

![image](https://github.com/user-attachments/assets/692951ff-d590-4ed4-8842-74ffb6a079c0)

**Comment by mrbaseman** [comment]
I have just pushed the proposed fix. Unfortunately, you didn't show the yaml file which causes the error, so I can't add a test for this to the testsuite. Anyhow, thanks for reporting and for the suggestion for improvement.
