### ISSUE TITLE
Bug: sed: 2: "s|^[[:space:]]*#.*||;s| ...": undefined label '1;t;:1;s|^[[:space:]]*$||;t2;p;:2;d'

### ISSUE THREAD

**Issue by prologic** [mrbaseman/parse_yaml#3]
I found a bug :)

But I have no idea how to fix it :/

This fails on the following input:

```sh
$ ./parse_yaml.sh user-data
sed: 2: "s|^[[:space:]]*#.*||;s| ...": undefined label '1;t;:1;s|^[[:space:]]*$||;t2;p;:2;d'

$ cat user-data
hostname: ulinux-test
manage_etc_hosts: true
user: root
disable_root: False
password: $5$SXUfZAMG$IPWDcNbmgl1A91OybwYZQcDhg2V4e0noOxojBt5z/78
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDo9UKNJ6X+LUxY9E2Ne3IxluaBTQWE0nCgyVfPHgSJhrI1HDiKcwc2S10kzMOnWco47sOb0Te4/tOHh+jlBbSTiW2CqQpIkZ8Bz4d1VXIPpUCUreP8gSuWxWNrdiU3TpfaeLSn0BkQhssvUhooAVPcRlgpmLETeGVlY1G2Qc1YcrQusz5E/5vLp4wkycZnGvHJ9+R5M2gn12Wnj+Fg8xMdqsvKmtBasPTX9YcJxVj/CBJZUB5impNg7ml9mESGDOpU11H9UWLUiDjIOmiDu3baNUiUmUnrUG44HBnstvbglEEOjsywML9xB81iZkA8RPluFpMU/+BWPI3nIKyRZn2p prologic@Jamess-MacBook.local
chpasswd:
  expire: False
package_upgrade: true
```

**Comment by prologic** [comment]
Looks like its b0rking on this line:

```
-ne "s|^$s#.*||;s|$s#[^\"']*$||;s|^\([^\"'#]*\)#.*|\1|;t1;t;:1;s|^$s\$||;t2;p;:2;d"
```

The first `sed` call.

**Comment by prologic** [comment]
Hmm I'm a bit stumped here I'm afraid. I've never used sed labels abd branches before. Didn't even know you could do this :)

**Comment by prologic** [comment]
I _believe_ this might ahve something to do with the fact I'm using non-GNU `sed` here. In fact this fails on OS X's `sed` as well as the busybox applet `sed`. Still haven't figured out how to fix this yet.

**Comment by mrbaseman** [comment]
thanks for this bug report. The code is not easy to read, I'm sorry. If you find a solution nevertheless, please submit a pull request. Otherwise, when I find some time I'll try to change the code to something more portable. Perhaps I should do it without labels in `sed` - which might mean that I should switch to `awk` for that subtask.

**Comment by prologic** [comment]
yeah I actually found a different solution entirely yaml.sh I think? That entirely uses awk and does a better job. Sorry :) But I needed to parse yaml in shell for [uLinux](https://github.com/prologic/ulinux) and I could not figure out this bug here in the end :/

**Comment by mrbaseman** [comment]
If I had seen that back then I wouldn't have reinvented the wheel ;)

**Comment by Cabral1988IO** [comment]
> ```shell
> true
> ```

**Comment by Cabral1988IO** [comment]
Cabral1988IO

**Comment by mrbaseman** [comment]
I think this is a portability issue. I can't reproduce it on linux. gnu `sed` has an option `--posix` and if I use that one, it doesn't fail, but the output is garbled. The strange thing in the error message described here is, the non-gnu `sed` knows labels but it seems that it takes the rest of the line as the label. maybe it's less common and more portable to use characters for labels than digits..
