### ISSUE TITLE
Incompatible with mawk 1.3.3

### ISSUE THREAD

**Issue by jgroman** [mrbaseman/parse_yaml#8]
mawk 1.3.3 doesn't support [[:space:]] character class: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=65617 and there are also subtle differences in `index()` function newlline character handling.

**Comment by mrbaseman** [comment]
closing this since the pull request has been merged. 
(if the PR were named 'Fix for #8' this issue would have been closed automatically)
